[LightDM]
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-gtk-greeter

autologin-user=user
autologin-user-timeout=0
autologin-session=vamora

user-session=vamora

greeter-hide-users=false
greeter-show-manual-login=false
allow-guest=false