backend = "xrender";
vsync = true;

opacity-rule = [];

blur-background-exclude = [
     "name = 'vamora-homescreen'"
]

frame-opacity = 1;
blur-background = true;
blur-background-frame = true;
blur-kern = "7x7box";

corner-radius = 12;
corner-radius-rules = [
     "0:fullscreen",
     "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_VERT' || _NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_HORZ'",
     "0:class_g *?= 'vamora-statusbar' || name *?= 'vamora-statusbar'",
     "0:class_g *?= 'vamora-dock' || name *?= 'vamora-dock'"
];

shadow-exclude = [
     "fullscreen",
     "class_g *?= 'vamora-statusbar' || name *?= 'vamora-statusbar'",
     "class_g *?= 'vamora-dock' || name *?= 'vamora-dock'"
];

saturation = 2;
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 10;

blur:
{
  method = "dual_kawase";
  strength = 12;
  background = true;
  background-frame = true;
  background-fixed = false;
};

shadow = true;
shadow-radius = 14;
shadow-opacity = 0.45;
shadow-offset-x = -15;
shadow-offset-y = -5;

blur-background-fixed = true;
